name: mi_recibo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:         # ğŸŒ necesario para espaÃ±ol (Material/Cupertino)
    sdk: flutter

  # UI / fuentes / Ã­conos
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # Firebase
  google_sign_in: ^6.2.1
  firebase_core: ^3.5.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.4.4

  # Archivos / guardado / permisos
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  media_store_plus: ^0.1.3   # âœ…

  # Compartir / PDF / enlaces
  url_launcher: ^6.3.0
  share_plus: ^10.0.2
  pdf: ^3.11.0
  printing: ^5.13.4

  # ğŸ” AutenticaciÃ³n biomÃ©trica (PIN/huella/FaceID)
  local_auth: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logoB.png
    - assets/images/google_logo.png
    - assets/images/logo_whatsapp.png
    - assets/images/logo_pdf.png
